on: [push, pull_request]

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          python3
          print("hi")
          a = 3
          print(a)
        working-directory: scripts
